version: '3'
services:
  nginx:
    image: nginx_proxy:0.2.1
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./content:/usr/share/nginx/html
